/**
 * QR broadcast creation helpers.
 *
 * This module provides the server-side functions for creating QR-based
 * WhatsApp broadcasts. It calls the `create_qr_broadcast_with_recipients`
 * Postgres RPC which handles deduplication, phone snapshotting, outbox
 * insertion, and deterministic idempotency keys in one atomic transaction.
 *
 * SECURITY: call only from server-side code (API routes / server actions).
 * Never import this in client components — it requires a service-role client.
 */

export interface QrBroadcastInput {
  accountId: string;
  userId: string;
  name: string;
  whatsappAccountId: string;
  messageText: string;
  contactIds: string[];
  scheduledAt?: Date | null;
  sendIntervalMs?: number;
  mediaUrl?: string | null;
  mediaType?: "image" | "video" | "document" | "audio" | null;
  mediaFilename?: string | null;
  mediaMimetype?: string | null;
}

export interface QrBroadcastResult {
  broadcastId: string;
  recipientCount: number;
}

export type QrBroadcastError =
  | { code: "NO_MESSAGE"; message: string }
  | { code: "NO_CONTACTS"; message: string }
  | { code: "INVALID_INTERVAL"; message: string }
  | { code: "DB_ERROR"; message: string };

/**
 * Derives the deterministic idempotency key for a QR broadcast job.
 * Must match the key generated by the Postgres RPC.
 *
 * Pure function — safe to use in tests without a DB.
 */
export function deriveIdempotencyKey(broadcastId: string, recipientId: string): string {
  return `broadcast:${broadcastId}:recipient:${recipientId}`;
}

/**
 * Validates a QrBroadcastInput and returns an array of error objects.
 * Empty array means valid.
 */
export function validateQrBroadcastInput(
  input: QrBroadcastInput,
): QrBroadcastError[] {
  const errors: QrBroadcastError[] = [];

  if (!input.messageText || input.messageText.trim() === "") {
    errors.push({ code: "NO_MESSAGE", message: "Message text is required for QR broadcasts." });
  }

  if (!input.contactIds || input.contactIds.length === 0) {
    errors.push({ code: "NO_CONTACTS", message: "At least one contact is required." });
  }

  const interval = input.sendIntervalMs ?? 1000;
  if (interval < 500) {
    errors.push({
      code: "INVALID_INTERVAL",
      message: "Send interval must be at least 500 ms for responsible throughput.",
    });
  }

  return errors;
}

/**
 * Creates a QR broadcast with recipients atomically via Postgres RPC.
 *
 * @param supabase - A Supabase client initialised with the service-role key.
 *                  Never pass an anon or user-session client.
 */
export async function createQrBroadcast(
  // Accept `any` for the client type so this file doesn't import
  // @supabase/supabase-js directly and can be tested with a mock.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: any,
  input: QrBroadcastInput,
): Promise<QrBroadcastResult> {
  const validationErrors = validateQrBroadcastInput(input);
  if (validationErrors.length > 0) {
    throw new Error(validationErrors.map((e) => e.message).join(" "));
  }

  const { data, error } = await supabase.rpc("create_qr_broadcast_with_recipients", {
    p_account_id: input.accountId,
    p_user_id: input.userId,
    p_name: input.name,
    p_whatsapp_account_id: input.whatsappAccountId,
    p_message_text: input.messageText.trim(),
    p_contact_ids: input.contactIds,
    p_scheduled_at: input.scheduledAt?.toISOString() ?? null,
    p_send_interval_ms: input.sendIntervalMs ?? 1000,
    p_media_url: input.mediaUrl ?? null,
    p_media_type: input.mediaType ?? null,
    p_media_filename: input.mediaFilename ?? null,
    p_media_mimetype: input.mediaMimetype ?? null,
  });

  if (error) {
    throw new Error(`QR broadcast creation failed: ${error.message}`);
  }

  const row = Array.isArray(data) ? data[0] : data;
  if (!row?.broadcast_id) {
    throw new Error("QR broadcast creation returned no broadcast_id.");
  }

  return {
    broadcastId: row.broadcast_id as string,
    recipientCount: (row.recipient_count as number) ?? 0,
  };
}
